PEDESTRIAN_MASS = 80  # kg
PEDESTRIAN_RADIUS = 0.5  # m

STANDARD_VELOCITY = 3  # m/s
MAXIMUM_VELOCITY = 8  # m/s

A_CONSTANT = 2e3  # N
B_CONSTANT = 0.08  # m

K1_CONSTANT = 1.2e5  # kgs^-2
K2_CONSTANT = 2.4e5  # kgm^-1s^-1

TIME_STEP = 0.125  # s

NAVEGABLE_MINIMUM_DISTANCE = .35

DANGER_MULTIPLIER = 1e4
DANGER_DISTANCE_RATIO = 12.5  # m
